name: PHPStan

on:
  - workflow_dispatch

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
      - name: PHPStan Static Analysis
        continue-on-error: true
        run: vendor/bin/phpstan analyse src/ inc/ --error-format=sarif  > phpstan-results.sarif
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: phpstan-results.sarif
          wait-for-processing: true
